# Generated by Django 4.0.5 on 2022-10-24 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bookModel_module', '0003_bookmodels_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(verbose_name='Is Paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.FloatField(blank=True, null=True, verbose_name='Final Pirce')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.order',
                                            verbose_name='Cart')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookModel_module.bookmodels',
                                   verbose_name='Product')),
            ],
        ),
    ]
