# Generated by Django 4.0.5 on 2022-10-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.FloatField(verbose_name='Count'),
        ),
    ]
