# Generated by Django 4.0.5 on 2022-10-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategoryModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='BookModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Book name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('description', models.TextField(max_length=2000, verbose_name='Descriptions')),
                ('image', models.ImageField(upload_to='bookimage', verbose_name='Book image')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('publisher', models.CharField(max_length=150, verbose_name='Published')),
                ('translator', models.CharField(blank=True, max_length=150, null=True, verbose_name='Translator')),
                ('language', models.CharField(max_length=100, verbose_name='Language')),
                ('year_of_publication', models.DateField(verbose_name='Create date')),
                ('number_of_pages', models.IntegerField(verbose_name='Pages')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Url')),
                ('active', models.BooleanField(default=False, verbose_name='Active:On/Off')),
                ('offer_price', models.IntegerField(blank=True, null=True, verbose_name='Offer Price')),
                ('category', models.ManyToManyField(to='bookModel_module.bookcategorymodels', verbose_name='Category')),
                ('subject', models.ManyToManyField(blank=True, null=True, to='bookModel_module.booksubjectmodel', verbose_name='Subject')),
            ],
        ),
    ]
