# Generated by Django 4.0.5 on 2022-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookModel_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodels',
            name='offer_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Offer Price'),
        ),
    ]
