# Generated by Django 4.0.5 on 2022-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookModel_module', '0002_alter_bookmodels_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodels',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Offer'),
        ),
    ]
